/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyContract } from "./MyContract";

export { MyContract__factory } from "./factories/MyContract__factory";
